import os
import logging
from dotenv import load_dotenv

# --- Загрузка .env и настройка логгирования ---
load_dotenv()
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - [%(funcName)s] - %(message)s')
logger = logging.getLogger(__name__)

# --- Основные переменные ---
MS_TOKEN = os.environ.get("MS_TOKEN")
if not MS_TOKEN:
    raise ValueError("ms_token не найден в .env файле.")

# --- Пути к файлам и папкам ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_FILE = os.path.join(BASE_DIR, "cache.db")
VIDEO_CACHE_DIR = os.path.join(BASE_DIR, "video_cache")
AUDIO_DIR = os.path.join(BASE_DIR, "audio_files")
TEMPLATE_FILE = os.path.join(BASE_DIR, "templates", "download_page.html")

# --- Настройки yt-dlp (проблемная строка УДАЛЕНА) ---
YDL_OPTIONS = {
    'format': 'bestaudio/best',
    'outtmpl': '', 
    'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}],
    'quiet': True,
    'no_warnings': True,
}

# --- Ваши YouTube Cookies ---
YOUTUBE_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789418570	VISITOR_PRIVACY_METADATA	CgJHQhIEGgAgYg%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787762858	__Secure-YEC	CgtNQXJLUTlnVTc0SSjKt_7EBjIKCgJHQhIEGgAgYg%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789850561	__Secure-3PSID	g.a0000QhpKEYXY_Srx5YXSEwxLbdO9iwRbryJ9RfVm_Jjw0cPS6P_L94JiZAWKD-l4sAhjtZF-wACgYKAeQSARYSFQHGX2MiG___OUfJG4WUwBz2fiV_8xoVAUF8yKr_7hC3sjaJABJ_SoS1USGr0076
.youtube.com	TRUE	/	FALSE	1786826571	SIDCC	AKEyXzUvZsJrFScP1F0WnK4cu5vHUWgIbYdjeoKF4PU_1zmrqnJ2UKn0QCZuA6nSIhi7cefkVA
#HttpOnly_.youtube.com	TRUE	/	FALSE	1755377688	YSC	R4HoWrWdWE8
.youtube.com	TRUE	/	FALSE	1789850561	SID	g.a0000QhpKEYXY_Srx5YXSEwxLbdO9iwRbryJ9RfVm_Jjw0cPS6P_bfanohItyNDjJrmSdd8WkwACgYKAc8SARYSFQHGX2MiYK2g7OeV3t4-x-LC3M_orhoVAUF8yKq1_WiS0HkItFMAS5snONbp0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1785170862	__Secure-1PSIDTS	sidts-CjIB5H03P-BUZE3gYlZYc4NPs77ru687PHJrf1SiweD4-M9kat_AqUtKfZDtzHEWGMQMuRAA
.youtube.com	TRUE	/	TRUE	1789850561	SAPISID	vkWki_pK-5GCWru7/A6RJhhF3E8EtYYI9K
#HttpOnly_.youtube.com	TRUE	/	TRUE	1786826571	__Secure-1PSIDCC	AKEyXzUdHzR8_5jDyBBC_m2W5__KmgUqtr9iXsP9lCwiuMUWEDlK_Q9eLBkdRXv_bHIXDNNNgA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789850561	SSID	A1NDcff85yot3pdGu
.youtube.com	TRUE	/	TRUE	1789850561	__Secure-1PAPISID	vkWki_pK-5GCWru7/A6RJhhF3E8EtYYI9K
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789850561	__Secure-1PSID	g.a0000QhpKEYXY_Srx5YXSEwxLbdO9iwRbryJ9RfVm_Jjw0cPS6P_70O0BuQ6d8D26yebIKl9MwACgYKAbsSARYSFQHGX2Mi7D_qZmWptV7EOurPg7WmuBoVAUF8yKqdzJ20fKpkHjQu-KfYypIp0076
.youtube.com	TRUE	/	TRUE	1789850561	__Secure-3PAPISID	vkWki_pK-5GCWru7/A6RJhhF3E8EtYYI9K
#HttpOnly_.youtube.com	TRUE	/	TRUE	1786826571	__Secure-3PSIDCC	AKEyXzXA8rfCIa0VtVaKKAZKow2TSuNLLKxD1ns6b7n6ty_RhP-qr7ieU2s3bHmrW-DSPNrvtQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1785170862	__Secure-3PSIDTS	sidts-CjIB5H03P-BUZE3gYlZYc4NPs77ru687PHJrf1SiweD4-M9kat_AqUtKfZDtzHEWGMQMuRAA
.youtube.com	TRUE	/	FALSE	1789850561	APISID	9nM45AqlT2N7eU7Z/AeN1IrcLT4S4qf2fa
#HttpOnly_.youtube.com	TRUE	/	FALSE	1789850561	HSID	AS1rt45dWIHGFRpWe
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788194863	LOGIN_INFO	AFmmF2swRgIhAIUnq9iCdnJW9eZXHeFEfdD0oA-frRYmFMFZpVcfPnkkAiEAheOPSmxtF85wfZToz8Afmp_vnhXza_RApLNQzQDANnY:QUQ3MjNmeGlEa0M0RFd5S1N4QndISHVCOFJ2NFdsT29EYlU2c0FqaWxpQTFVT2NkdUlkMmpTdFlOSDhKSWRWOHpOaFRGXzdiRzlmai1lTk95a2xZNm1OUm0tdVZaZVZRbFRacXI1TFJIaUtJNC1jbmhmRUk0ME1lNHZBMjdHOVhiODVVeFVlb0FMaXFGemxyZ094VzJqSEVleVFYSXVhYy1n
.youtube.com	TRUE	/	TRUE	1789850570	PREF	tz=Europe.Moscow
.youtube.com	TRUE	/	FALSE	1753634879	ST-1nu4587	csn=CttDRyNBp3r2IF1z&itct=CE8Q_FoYASITCIrzqfm-3Y4DFf78OwIdQX4FRlIHeW91dHViZZoBBQgyEPQk
"""